#import "@preview/ergo:0.1.1": *

#import "@local/superTemplate:0.3.0": *
#import math_mod:*
#import pstat_mod:*
#import cs_mod: *

#show: ergo-init.with(colors: "gruvbox-dark", headers: "classic")
#let title = "math111a hw3"
#let author = "jc"
#let date = datetime.today()
#show: assignment.with(title, author, date)

#problem[Find the order of the permutation $cyc(1,12,8,10,4) cyc(2 ,13) cyc(5, 11, 7) cyc(6, 9)$ ][

(from problem 3) we know that the order  must be the LCM of ${5,2,3}$ which is 30 

]

#problem[Let $sigma $ be a k-cycle. Prove that $sigma^i $ is also a k-cycle if and only if $i $ is relatively prime to $k$ ][

Note that $sigma^i (a_j) = a_(j+i mod k)$ where if $j+i>k$ then we mod $j+i$ by $k$

This is because, mod $k$ we have  $ sigma^i (a_j) = sigma^(i-1) sigma(a_j) = sigma^(i-1) (a_(j+1)) = sigma^(i-2) sigma(a_(j+1)) = sigma^(i-2) (a_(j+2))=dots=sigma^(i-i) sigma(a_(j+i-1)) = a_(j+i) $ 

Using this fact, we that continuous applications of $sigma^i$ to $a_k$ will yield $ a_(k) arrow.bar a_(k+i) arrow.bar a_(k+2i) arrow.bar dots arrow.bar a_(k+(k-1)i) arrow.bar a_k $

Since each $k + x i, k + y i$ are distinct then we have $k+x i equiv.not k + y i arrow.double i(x-y) equiv.not 0$ $mod k$   

Next we need to show that $i(x-y) equiv.not 0 mod k arrow.double.l.r (i,k)=1$

$arrow.double.r$ 

Suppose $(i,k)=d > 1$ then let $i=i' d, k = k' d$

Then $i' d (x-y) equiv.not 0 mod k'd arrow.double k' d divides.not i' d (x-y) arrow.double k' divides.not i' (x-y)$ 

$arrow.double.l $ is true since $x-y eq.not 0$ and $i$ cannot be a factor of $k$ by coprime definition

$qed$ 

Sources: \
(1) https://www.uvm.edu/~mrombach/251-H2-sols.pdf \
(2) https://math.stackexchange.com/questions/659222/let-sigma-be-the-m-cycle-1-2-ldots-m-prove-that-sigma-i-is-also-a

]
#pagebreak()
#problem[Prove the the order of an element in $S_n $ equals the least common multiple of the lengths of the cycle in the cycle decomposition][

Note that a $k $ cycle will have order $k $ 

Therefore, for some $k $ cycle $sigma $ we have $sigma^(k) = 1 = sigma^(n k)$ for some $n in ZZ$ \

If some $sigma in S_n$ has (disjoint) cycle decomposition such that $sigma = tau_1 dots tau_m$ where $tau_i in S_n, i in {1,dots,m}$  then $ sigma^r = (tau_1 dots tau_m)^r = tau_1^r dots tau_m^r = 1 arrow.double.l.r tau_1^r = 1, dots, tau_m^r = 1 $

Where the second equality holds due to $tau_1, dots, tau_m$ being disjoint cycles, recall disjoint cycles commute with eachother 

Therefore the order of $sigma$ denoted $r$ must be a multiple of each of $|tau_1|, dots, |tau_m|$ 

Furthermore, this multiple must be as small as possible, or in other words $r$ is the least common multiple of the orders, or in other words the least common multiple of the lengths of the cycle

$qed$  

]
#problem[Prove that every $sigma in S_n $ can be written as a product of adjacent elements, that is, transpositions of the form $(i, i+1)$. This was one of the exercises I had given in class  ][

  From class, we know that every $sigma in S_n$ can be written as a product of disjoint cycles \

  Also, we know that any cycle $cyc(a_1, a_2, dots, a_k)=(a_1 a_2)(a_2 a_3) dots (a_(k-1) a_k)$ where $a_1 dots a_k$ are distinct  \

  Any transposition $cyc(a,b)$ where $a < b$ can be written as (i) $ cyc(a b) = cyc(a, a + 1)· · ·cyc(b - 2, b - 1)cyc(b - 1, b)cyc(b - 2, b - 1)· · ·cyc(a, a + 1) $  \

  In the case of $cyc(a, b)$ where $a > b$ consider (constructed by the above), $ cyc(b, a) = (b, b + 1)· · ·cyc(a-2,a-1)cyc(a-1,a)cyc(a-2,a-1)· · ·cyc(b, b+1) $  

  And $ cyc(b, a)^(-1) = cyc(b, b+1)· · ·cyc(a-2, a-1)cyc(a-1,a)cyc(a-2,a-1)· · ·cyc(b,b+1) = cyc(a,b) $ 

  Since $(sigma_1 dots sigma_n)^(-1) = sigma_n^(-1) dots sigma_1^(-1)$ and a two cycle is its own inverse

  $qed$

  example: 

  (1 2)(2 3)(1 2)  = (1 3) \

  (3 1) = (1 2) (2 3) ( 1 2)

  references: \
  (i) https://www.albany.edu/~am815139/327.2015.ReviewExam2Sol.pdf \
  ]
#pagebreak()
#problem[Prove that for all $n gt.eq 2$ the set $S_n $ is generated by the elements $cyc(1,2) "and" cyc(1,2,dots,n)$  ][

Consider that $ cyc(1,2,dots,n) cyc(1,2) cyc(1,2,dots,n)^(-1) &= cyc(2,3) \ cyc(1,2,dots,n)cyc(2,3)cyc(1,2,dots,n)^(-1)&=cyc(3,4) \ &dots.v \ cyc(1,2,dots,n)cyc(n-2,n-1)cyc(1,2,dots,n)^(-1) &= cyc(i,i+1) $ for $1 lt.eq i lt.eq n-1$

By problem 4, we know that each $sigma in S_n$ can be written as a product of elements of the form $cyc(i,i+1)$

Since $cyc(1,2)$ and $cyc(1,2,dots,n)$ generates such elements, they also generate $S_n$

$qed$ 
  
]
#pagebreak()
#problem[Let $G$ be an Abelian group. Prove that the set ${g in G : |g| < infty}$ is a subgroup of $G $. This is called the torsion subfroup of $G$. Give an example where this set is not a subgroup when $G $ is non-abelian  ][

Denote $H := {g in G:|g|<infty}$ 

We can try to show that $H eq.not emptyset$ and that $forall x,y in H$ that $x y^(-1) in H$ \

First, note that $1 in G$ has order 1 so that $H eq.not emptyset$

Also, if $x in H, y in H$ let their orders be $|x|=n, |y|=m arrow.double |y^(-1)|=m$ then $(x y^(-1))^(n m) = x^(n m) (y^(-1))^(n m) = 1^m 1^n = 1$ and therefore $x y^(-1)$ has order $n m$ and is in $H$   

We can recall that since $G$ is abelian and $x,y in G$ that $(x y)^n = x^n y^n$ for all $n in ZZ$ and that an element and its inverse have the same order (homework 2) $qed$

Consider the non-abelian group $G L_2 (QQ) = {A_(2 times 2)(QQ):det A eq.not 0}$ \

Note that $mat(0,-1;1,0)$ has order 4 and $mat(0,1;-1,-1)$ has order 3, but $mat(0,-1;1,0) mat(0,1;-1,-1)=mat(1,1;0,1)$ which has infinite order (since $mat(1,1;0,1)^n = mat(1,n;0,1)$ ), and therefore the set ${g in GL_2(QQ):|g|<infty}$ is not closed, and therefore not a subgroup    

References:

https://en.wikipedia.org/wiki/General_linear_group

]
#problem[

1. Prove that if $H $ and $K $ are subgroups of a group $G$, then so is their intersection $H sect K$  

2. Prove that the intersection of an arbitrary non-empty collection of subgroups of a group $G $ is again a subgroup of $G$ (do not assume the collection is countable) 

][

1. Firstly, $1 in G arrow.double 1 in H and 1 in K arrow.double 1 in H sect K$

Secondly, $a,b in H sect K arrow.double a in H and a in K and b in H and b in K arrow.double a b in H and a b in K arrow.double a b in H sect K$

Thirdly, $a in H sect K arrow.double a in H and a in K arrow.double a^(-1) in H and a^(-1) in K arrow.double a^(-1) in H sect K$

Where each part is justified by properties of subgroups $qed$ 

2. Let $H_1 dots H_2 dots$ be a collection of subgroups of $G$, then since each pair of $H_i$ is a subgroup from part a) we know that their intersection $((H_1 sect H_2) sect H_3)sect dots$ will also be a subgroup, similar to generalized associative law. $qed$ 

]
#problem[Let $H_1 lt.eq H_2 lt.eq dots$ be an asecnding chain of subgroups of a group $G$. Prove that $union_(i=0)^infty H_i$ is a subgroup of $G$     ][

We can combine the following facts:

1. if $A subset.eq B$ and $B subset.eq C$ then $A union B subset.eq C$

2. $H_1 union H_2$ is a subgroup iff $H_1 subset.eq H_2$ or $H_2 subset.eq H_1$   

For fact a note that $x in A union B arrow.double x in A or x in B$. If $x in B arrow.double x in C$ and if $x in A arrow.double x in B arrow.double x in C$ by the initial assumption \

For fact b we can use a weaker version which is that $H_1 subset.eq H_2 arrow.double H_1 union H_2$ is a subgroup

To show this, consider that (by definition)$H_1 subset.eq H_2 arrow.double H_1 union H_2 = H_2$ and that $H_2$ is a subgroup by assumption  

Next, $H_1 union H_2 subset.eq H_3 arrow.double H_1 union H_2 union H_3 = H_3$ is a subgroup and we can keep applying fact b then fact a and conclude that $union_(i=0)^infty H_i$ is a subgroup of $G$

$qed$ 

references:\
https://math.stackexchange.com/questions/3634918/for-two-subgroups-h-1-h-2-how-can-i-show-h-1-cup-h-2-is-subgroup-iff

]
#problem[

In both parts (i) and (ii) prove that the specified subset is not a subroup of the given group

(i) the set of 2-cycles in $S_n $ for $n gt.eq 3$ 

(ii) the set of reflections in $D_(2 n)$ for $n gt.eq 3$  

][

(i) $cyc(1,2) cyc(1,3) = cyc(1,3,2)$ which is a 3 cycle, and the set is not closed

(ii) From homework 2 we know that two successive reflections are equivalent to a rotation $arrow.double$ set is not closed 

]
