#import "@preview/ergo:0.1.1": *

#import "@local/superTemplate:0.3.0": *
#import math_mod:*
#import pstat_mod:*
#import cs_mod: *

#show: ergo-init.with(colors: "gruvbox-dark", headers: "classic")
#let title = "math111a hw4"
#let author = "jc"
#let date = datetime.today()
#show: assignment.with(title, author, date)

#definition[The centaliser of a subset][
Let $G$ be a group and $A subset.eq G$

The centraliser of $A$ is the set $C_G (A) = {g in G: g a g^(-1)=a forall a in A} = {g in G : g a = a g forall a in A}$  
]

#definition([Normalizer of a group],[
Let $G $ be a group and $A subset.eq G$

For $g in G$ define $g A g^(-1) = {g a g^(-1): a in A}$

The normaliser of $A$ in $G$ is defined as $N_G (A) = {g in G: g A g^(-1) = A}$   
])

#prob(breakable: true)[In each part show that for the specified group $G$ and subgroup $A$ of G, $C_G (A) = A$ and $N_G (A) = G$ 

1. $G = S_3$ and $A = {1,cyc(1,2,3),cyc(1,3,2)}$  
2. $G = D_8$ and $A={1,s,r^2,s r^2}$  
3. $G = D_10$ and $A = {1,r,r^2,r^3,r^4}$  
   ][
First we show $C_G (A) = A$ for each part  

1. Let $sigma in A$ then since $A$ is cyclic and abelian, then $sigma in C_(S_3) (A)$   

The other elements of $S_3$ not in $A$  are ${cyc(1,2),cyc(2,3),cyc(1,3)}$ (let;s check if they commute with $cyc(1,2,3)$ )

We can check $cyc(1,2,3) cyc(1,2) = cyc(1,3)$ and $cyc(1,2) cyc(1,2,3) = cyc(2,3)$  

We can check $cyc(1,2,3)cyc(2,3) = cyc(1,2)$ and $cyc(2,3)cyc(1,2,3) = cyc(1,3)$

We can check $cyc(1,2,3)(1,3) = cyc(2,3)$ and $cyc(1,3)cyc(1,2,3)=(1,2)$

Therefore $C_S_3 (A )$ cannot have elements outside of $A therefore sigma in C_S_3 (A) arrow.double sigma in A$ and $C_S_3 (A) = A$   

2. From the Cayley table for $D_8$ in homework 2, we can verify that all elements of $A$ commute with eachother. Therefore $x in A arrow.double x in C_(G) (A)$

The other elements in $D_8$ are ${s r, s r^3, r, r^3}$ (let's see if they commute with $s$ )

We can check $(s r) (s) = s r s = s s r^(3) = r^3 eq.not  r = (s) (s r)$ \
We can check $(s r^3)(s) = s r^3 s = s s r = r eq.not r^3 = (s)(s r^3)$  \
We can check $(r) (s) = s r^3 eq.not (s) (r)$ \
We can check $(r^3)(s) = s r eq.not (s)(r^3)$

Therefore $C_D_8 (A)$ cannot have elements outside of $A therefore x in C_D_8 (A) arrow.double x in A$ and $C_D_8 (A) = A$

3. Since $A$ is the cyclic group generated by $r$ then $A$ is abelian and $x in A arrow.double x in C_D_10 (A)$ 

The other elements in $D_10 $ are ${s, s r, s r^2, s r^3, s r^4}$ (let's see if they commute with $r$ )

We can check $s r eq.not r s$, $s r r = s r^2 eq.not s = r s r$, $s r^2 r = s r^3 eq.not r^4 s =  r s r^2$, $s r^3 r = s r^4 eq.not r^3 s = r s r^3$, and finally $s r^4 r = s eq.not r^2 s = r s r^4$    

Therefore (similar to above) $x in C_D_10 (A) arrow.double x in A$ and $C_D_10 (A) = A$ \ $square$ 


Next, we show $N_G (A) = G$ for each part \

(handwritten)


   ]

#pagebreak()
#prob[Let $H $ be a subgroup of group $G$. 

1. Show that $H lt.eq N_G (H)$. give an example to show this is not necessarily true if $H $ is not a subgroup of $G$    

2. Show that $H lt.eq C_G (H)$ iff $H $ is abelian 
 ][

1. Since $H$ is a subgroup, it is closed and inverses exist, therefore we only need to show that $H subset.eq N_G (H)$  

Let $h in H$, then we would like to show that $h H h^(-1) = H$ \

$subset.eq$ let an element $z in h H h^(-1)$, then $z = h h'h^(-1)$ where $h' in H$. Since $H$ is closed, then $z in H$ \

$supset.eq$ let an element $z in H$ then we want to show that $z = h h' h^(-1)$ for some $h' in H$. Since $H $ is closed, then $h h' h^(-1) in H$ and we can set $h' = h^(-1) z h in H$ to obtain the desired result.    \

The claim follows.

$qed$ 

Say that $H$ is only a subset of $G$ say $H = {cyc(1,2),cyc(1,3)} subset.eq S_3 = G$ 

Then $cyc(1,2) cyc(1,2) cyc(2,1) = () in.not H$ and $cyc(1,2)cyc(1,3)cyc(2,1) = cyc(2,3) in.not H$

If $cyc(1,2) in H$ is in $N_S_3 (H)$ then it has to normalize something in $H$, but the above show it does not, therefore $x in H arrow.double.not x in N_S_3 (H)$ in this case $therefore H lt.eq.not N_S_3 (H)$       

2. $arrow.double$ let $x in H$ then $x in C_G (H) arrow.double x h = h x forall h in H arrow.double x h = h x forall h,x in H$ (since $x$ was chosen arbitrarily) which means that $H$ is abelian 

$arrow.double.l$ Let $H$ be abelian then we want to show $H subset.eq C_G (H)$

Let $x in H$ then $x h = h x forall h,x in H "by assumption" arrow.double x in C_G (H)$ by definition, and since $H$ is closed and inverses exist then $H lt.eq C_G (H)$   

$qed$ 

 ]
#pagebreak() 
#prob[Find all generators of $ZZ_48$ ][

1, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47

Since the generators of $ZZ_n$ must be coprime to $n$, which come from the fact that if $H = angle.l x angle.r$ and $abs(x) = n < infty$ then $x^a$ generates $H$ iff $(a,n)=1$. Here $x=1$ with order $n=48$    

Sources:

David and Foote proposition 6.2, Section 2.3


]
#prob[What is the order of $overline(30) in ZZ_54$? Write out all the elemtns and their orders in $angle.l overline(30) angle.r$  ][

The order is $54 slash (30,54) = 54 slash 6 =9$ (by the proposition from class) \

The elements of the subgroup generated by $overline(30)$ are ${overline(0),overline(30),overline(6),overline(36),overline(12),overline(42),overline(18),overline(48),overline(24)}$ with orders ${1,9,9,3,9,9,3,9,9}$ respectively, by the same proposition 

Sources:

David and Foote proposition 5.2, Section 2.3

]
#prob[Find all the cyclic subgroups of $D_8 $ . Find a proper subgroup $D_8 $ that is not cyclic][

Note that $D_8 = {1,r,r^2,r^3,s, s r, s r^2, s r^3}$, the cyclic subgroups are 

$angle.l 1 angle.r = {1}$ \

$angle.l s angle.r = {1,s}$ since $s^2 = 1$ \

$angle.l s r angle.r = {1, s r}$ since $s r s r = s r r^(-1) s = s^2 = 1$

$angle.l s r^2 angle.r = {1, s r^2}$ since $s r^2 s s^2 = s r^2 r^(-1) s = 1$

$angle.l s r^3 angle.r = {1, s r^3}$ by similar reasoning

$angle.l r angle.r = {1,r, r^2, r^3}$ 

$angle.l r^2 angle.r = {1,r^2}$

$angle.l r^3 angle.r = {1,r^3, r^2, r^1} = angle.l r angle.r$

A subgroup that is not cyclic is $angle.l s,r^2 angle.r = {1,r^2,s,s r^2}$ but each of $1, s, r^2, s r^2$ by itself cannot generate $angle.l s, r^2 angle.r$ (see the subgroups above), this is a subgroup of $D_8$  since it is closed and a non-empty finite subset of $D_8$  

]
#prob[Prove that if $x $ is the only element of order 2 in a group, then $x $ lies in the centre of the group][

Let $x in G$ where $G $ is a group and asume that that $x^2 = 1$  

Note that for all $g in G$  the element $g x g^(-1)$ also has order 2 since $(g x g^(-1)) (g x g^(-1)) = g x g^(-1) g x g^(-1) = e$

By assumption, this means ($forall g$ )that $x = g x g^(-1) arrow.double x g = g x$ i.e. that $x$ is in the center of $G $ 

$qed$ 

]
#prob[1. Prove that $D_6$ does not have a subgroup of order 4 \ 
2. Let $H $ be a subgroup of $D_(2 n)$ of of odd order. Prove that every member of $H $ is a rotation ][

1. $D_6 = {e,r,r^2,s,s r, s r^2}$ so there are 6 choose 4 = $6!/((6-4)!4!) = 15$ possible sets of $D_6$ with 4 elements   
$

{e, r, r^2, s} : r dot r^2 = r^3 arrow.double "not closed" \
{e, r, r^2, s r}: r dot r^2 = r^3 arrow.double "not closed"\
{e, r, r^2, s r^2}: r dot r^2 = r^3 arrow.double "not closed"\
{e, r, s, s r}: r dot s = r s eq.not s r arrow.double "not closed" \
{e, r, s, s r^2}: s dot s r^2 = r^2 arrow.double "not closed" \
{e, r, s r, s r^2}: r dot s r = r r^(-1) s = s arrow.double "not closed" \
{e, r^2, s, s r} : r^2 dot r^2 = r^4 = r^1 = r arrow.double "not closed" \
{e, r^2, s, s r^2} : r^2 dot r^2  = r arrow.double "not closed" \
{e, r^2, s r, s r^2} : r^2 dot s r = r^2 dot r^(-1) s = r s arrow.double "not closed" \
{e, s, s r, s r^2} : s dot s r = r arrow.double "not closed" \
{r, r^2, s, s r} : "no identity"\
{r, r^2, s, s r^2} : "no identity"\
{r, r^2, s r, s r^2} : "no identity"\
{r, s, s r, s r^2} : "no identity"\
{r^2, s, s r, s r^2} : "no identity"$

Then $D_6$ does not have a subgroup of order 4 (also by lagrange theorem)

2.

Note that the order of $H $ is finite, since it is a subgroup of a finite group.

If $H$ is a finite group and $x in H$ , then the order of $x$  divides the order of $H$. If such an $x$ is a reflection, it must have order 2 but $2 divides.not |H|$  since $|H|$ is odd. Therefore, $H$ can only contain rotations. To see that such an $H$ exists, consider the subgroup $angle.l r angle.r lt.eq D_10$ where $angle.l r angle.r = {e,r,r^2,r^3,r^4}$  

Sources:

David and Foote, Proposition 9, Section 3.2

https://homepages.math.uic.edu/~groves/teaching/2008-9/330/09-330HW7Sols.pdf

]
#pagebreak()
#definition([centre of a group],[

the centre of a group is defined as $Z(G) = {g in G : g x = x g forall x in G}$

#note[$Z(G) = C_G (G)$ and is a subgroup of $G$] 

])

#definition[Centraliser of an element][
Let $G $ be a group and $a in G$ fixed

The centraliser of $a $  in $G $ is the set $C(a)={g in G: g a g^(-1) = a} = {g in G : g a = a g}$ 

]

#prob[Let $G $ be a group. Show that $Z(G) = sect_(a in G) C(a)$ ][show set equality

$subset.eq$ \
Let $g in Z(G)$ then $g a = a g forall a in G$. \
Fix any $a in G$ then $g in {g in G:g a = a g} = C(a)$ \
Then $g in sect_(a in G) C(a)$ 

$supset.eq$ \
Let $g in sect_(a in G) C(a)$ then for any $a in G$ we have $g in C(a)$  i.e. that $g a = a g forall a$ \

This implies that $g in {g in G:g a = a g forall a in G} = Z(G)$

$qed$ 

]


#prob[Let $G $ be an abelian group and $H = {x in G: abs(x) "is odd"}$Prove that $H $ is a subgroup of $G$  ][

Firstly, $1 in H$ since $|1| = 1$ therefore $H eq.not emptyset$ \

Next, note that $forall x in H, |x^(-1)| = |x| arrow.double abs(x^(-1)) "is odd" arrow.double x^(-1) in H$

Next, let $a,b in H$ and set the orders $m:=abs(a), n:=abs(b), r :=lcm(m,n)$ $arrow.double r = m k, r = n l$ for some integers $k,l$

Then $(a b)^r = a^r b^r = a^(m k) b^(n l) = (a^m)^k (a^n)^l = 1$ since $G$ is abelian, therefore the order of $a b$ is $r = lcm(m,n)$

Since $m,n$ are odd then $lcm(m,n)$ is $"odd"^1$ and therefore $a b$ has odd order i.e. $a b in H$

Then since $H$ is a subset of $G$, finite, closed, and each element of $H$ has an inverse in $H$ then the claim follows. $qed$     

$1$: since $a b = gcd(a,b) dot lcm(a,b)$ (for positive integers $a,b$ )

Sources:

https://math.hawaii.edu/~allan/AdditionalGroupTheory.pdf

https://en.wikipedia.org/wiki/Least_common_multiple

]