#import "@preview/ergo:0.2.0": *

#show: ergo-init.with(
    colors:     ergo-colors.dracula,
    styles:     ergo-styles.sidebar1,
    breakable:  true,
    inline-qed: true,
    prob-nums:  true,
)

#set page(margin: 0.5in) 
#let title = "math111a hw6"
#let author = "jc"
#let inverse = (-1)
#let iff = $arrow.double.l.r$
#let normal = $lt.eq.tri$
#let implies = $arrow.double$

math111a jc hw9

#prob[Let $N normal G $ If $N $ is cyclic, prove every subgroup of $N  $ is also normal in $G $ ][]
#prob[Show by example that if in a factor group $G slash H $ it can happen that $abs(a H) = abs(b H)$ but $abs(a) eq.not abs(b)$  ][]
#prob[Prove that every subgroup of $D_(2 n)$ of odd order is cyclic ][]
#prob[Prove that for $n gt.eq 3$ the group $A_n$ is generated by the set of 3 cycles  ][]
#prob[Show that $ZZ $ has infinitely many subgroups isomorphic to $ZZ$ ][]
#prob[Prove that an infinite group must have an infinite number of subgroups][]