#import "@local/superTemplate:0.1.3": *
#import math_mod:*
#import pstat_mod:*

#let title = "cs 178 lecture notes"
#let author = "Alice and Bob"

#show: notes.with(title, author)

= January 6

#remark(
  [Cryptoraphy is about protecting data \ Examples: email services (tamper resistance) \ Web Browsers (domain
    authentiation) \ Electronic Voting (double counting) \ Proprietary Software (sofrware piracy/duplication) \ AI (privacy
    preserving ML, adversarial attacks, fariness, watermarking)],
)

#remark([Cryptosystem: problem, definition, construction, proof])

#example([private key encryption], [Alice and Bob are far away from eachother and want communicate \

  Assume: Bob will receive the correct message (message will not be tampered with) \

  Want to show: no one can learn the message (say in the presence of eavesdropper Eve)

  Three algorithms: ENC, DEC, GEN \

  ENC: $m arrow^k C T$ where $C T$ is a ciphertext \
  DEC: $C T arrow^k m$ \
  GEN: generates secret key $k$ shared by Alice and Bob \
  
  Here, GEN and ENC are probabilistic while DEC is deterministic ])

#remark(
  [Kerchoff's principle: despite public knowledge of cryptographic knowledge, the cryptosystem can still be shown to be
    secure.],
)

= January 10 section

NIST \


security (safe against adversary) \

integrity (message authenticity i.e. verify a message was generated by Alice instead of Eve) \

keys could be thought as a binary string \

definitions of security in private key cryptosystem setting \

caesar and vignere ciphers \






